mysql:
  image: mysql
  volumes:
    - /var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: ahfeiuhif3434kjsfkjsh273827pppp

memcached:
  image: memcached
  command: memcached -m 64

web:
  build: .
  links:
    - mysql
    - memcached
  volumes:
    - ./:/var/www
  ports:
    - "9001:80"
